
Normalisation and CTE queries

Assignment Questions

U First Normal Form (1NF)>
H Identify a table in the Sakila database that violates 1NF. Explain how you would normalize it to achieve 1NFa
U Second Normal Form (2NF)>
H Choose a table in Sakila and describe how you would determine whether it is in 2NF. If it violates 2NF,
explain the steps to normalize ita
U Third Normal Form (3NF)>
H Identify a table in Sakila that violates 3NF. Describe the transitive dependencies present and outline the
steps to normalize the table to 3NFa

U Normalization Process>
H Take a specific table in Sakila and guide through the process of normalizing it from the initial
unnormalized form up to at least 2NFa

U CTE Basics>
H Write a query using a CTE to retrieve the distinct list of actor names and the number of films they have
acted in from the and tablesa

U Recursive CTE>
H Use a recursive CTE to generate a hierarchical list of categories and their subcategories from the
table in Sakilaa

U CTE with Joins>
H Create a CTE that combines information from the and tables to display the film title, language
name, and rental ratea

U CTE for Aggregation>

H Write a query using a CTE to find the total revenue generated by each customer (sum of payments) from
the and tablesa

U CTE with Window Functions>

H Utilize a CTE with a window function to rank films based on their rental duration from the tablea

U CTE and Filtering>

H Create a CTE to list customers who have made more than two rentals, and then join this CTE with the
table to retrieve additional customer detailsa

U CTE for Date Calculations>

H Write a query using a CTE to find the total number of rentals made each month, considering the
from the tablea

U CTE for Pivot Operations>

H Use a CTE to pivot the data from the table to display the total payments made by each customer in
separate columns for different payment methodsa

U CTE and Self-Join>

H Create a CTE to generate a report showing pairs of actors who have appeared in the same film together,
using the tablea

U CTE for Recursive Search>

H Implement a recursive CTE to find all employees in the staff table who report to a specific manager,
considering the column.
actor film_actor

