xcreate database Mavenmovies;
Use Mavenmovies;

/*
Question 1:
Retrieve the total number of rentals made in the  database.
Hint: Use the COUNT() function.
*/

select * from rental;


#Answer--16044

select count(rental_id) from rental;

/*
Question 2:
Find the average rental duration (in days) of movies rented from the Sakila database.
Hint: Utilize the AVG() function.
*/

#Answer--5.0252

select * from rental;

select avg(datediff(return_date, rental_date)) from rental 
where return_date is not null;

# WHERE return_date IS NOT NULL: This condition ensures that only completed rentals are considered in the average calculation.


/*
Question 3:
Display the first name and last name of customers in uppercase.
Hint: Use the UPPER () function.
*/

select * from customer;

select upper(concat(first_name," ", Last_name)) as Full_Name from customer;

/*
Question 4:
Extract the month from the rental date and display it alongside the rental ID.
Hint: Employ the MONTH() function.
*/

select * from rental;

select rental_id, month(rental_date) from rental;

/*
Question 5:
Retrieve the count of rentals for each customer (display customer ID and the count of rentals).
Hint: Use COUNT () in conjunction with GROUP BY.
*/

select * from rental;
select * from customer;

select concat(c.first_name," ",c.last_name) as Full_name ,c.customer_id,count(r.customer_id) as Total_Rentals
from customer c 
inner join rental r on c.customer_id=r.customer_id
group by r.customer_id;



/*
Question 6:
Find the total revenue generated by each store.
Hint: Combine SUM() and GROUP BY.
*/


select s.store_id,sum(p.amount) 
from store s 
inner join staff st on s.store_id=st.store_id
inner join payment p on st.staff_id=p.staff_id
group by s.store_id;



/*
Question 7:
Display the title of the movie, customer s first name, and last name who rented it.
Hint: Use JOIN between the film, inventory, rental, and customer tables.
GROUP BY:
Joins:
*/


select f.title,concat(c.first_name,' ',c.last_name) as Customer_Name
from customer c 
inner join rental r on c.customer_id= r.customer_id
inner join inventory i on r.inventory_id= i.inventory_id
inner join film f on i.film_id=f.film_id;


/*
Advanced Joins and GROUP BY:

Mastering full stack data analytics

Assignment Questions
*/


/*
Question 8:
Retrieve the names of all actors who have appeared in the film "Gone with the Wind."
Hint: Use JOIN between the film actor, film, and actor tables.
*/

select concat(a.first_name,' ', a.last_name) as Full_Name
from actor a 
inner join film_actor fa on a.actor_id=fa.actor_id
inner join film f on fa.film_id=f.film_id
where f.title='GONE TROUBLE';


/*
Question 1:
Determine the total number of rentals for each category of movies.
Hint: JOIN film_category, film, and rental tables, then use cOUNT () and GROUP BY.
*/

select * from rental;
select * from inventory;
select * from film_category;
desc film_category;
select * from film;

select
fc.category_id,
count(r.rental_id) as Total_Count
from inventory i
inner join rental r on i.inventory_id=r.inventory_id
inner join film f on i.film_id=f.film_id
inner join film_category fc on f.film_id=fc.film_id
group by fc.category_id;


/*
Question 2:
Find the average rental rate of movies in each language.
Hint: JOIN film and language tables, then use AVG () and GROUP BY.
*/

select * from film;
select * from language;

select l.language_id,l.name,avg(f.rental_rate)
from language l
inner join film f on l.language_id=f.language_id
group by l.language_id,l.name;


/*
Question 3:
Retrieve the customer names along with the total amount they've spent on rentals.
Hint: JOIN customer, payment, and rental tables, then use SUM() and GROUP BY.
*/

select * from customer;
select * from rental;
select * from payment;

select concat(c.first_name,' ',c.last_name) as Full_Name,sum(p.amount) Total_Spent
from customer c 
inner join rental r on c.customer_id=r.customer_id
inner join payment p on r.rental_id=p.rental_id
group by c.customer_id;


select concat(c.first_name,' ',c.last_name) as Full_Name,sum(p.amount)
from customer c 
inner join rental r on c.customer_id=r.customer_id
inner join payment p on r.customer_id=p.customer_id
group by c.customer_id;

    
/*
Question 4:
List the titles of movies rented by each customer in a particular city (e.g., 'London').
Hint: JOIN customer, address, city, rental, inventory, and film tables, then use GROUP BY.
*/


select * from customer;
select * from rental;
select * from inventory;
select * from film;
select * from store;
select * from address;
select * from city;


select
f.title,concat(c.first_name,' ',c.last_name) as Customer_Name,cty.city
from customer c
inner join rental r on c.customer_id=r.customer_id
inner join inventory i on i.inventory_id=r.inventory_id
inner join film f on i.film_id=f.film_id
inner join address a on c.address_id=a.address_id
inner join city cty on a.city_id=cty.city_id
where cty.city_id=312
order by f.title
;


/*
Question 5:
Display the top 5 rented movies along with the number of times they've been rented.
Hint: JOIN film, inventory, and rental tables, then use cOUNT() and GROUP BY, and limit the results.
*/

select * from film;
select * from inventory;
select * from payment;
select * from rental;

select f.film_id,f.title,count(r.rental_id) as Total_Rental
from film f
inner join inventory i on f.film_id=i.film_id
inner join rental r on i.inventory_id=r.inventory_id
inner join payment p on r.rental_id=p.rental_id
group by f.film_id,f.title
order by Total_Rental desc
limit 5;



/*
Question 6:
Determine the customers who have rented movies from both stores (store ID 1 and store ID 2).
Hint: Use JOINS with rental, inventory, and customer tables and consider COUNT() and GROUP BY.
*/

count(distinct store_id)=2

select * from customer;

select * from rental;
1-harsha  5 1-foody
1-harsha  6 1-foody
1-harsha 15 2-Tasty

select count(distinct customer_id) from rental;
select * from inventory;
select * from store;

select 
c.customer_id,
concat(c.first_name,' ',c.last_name) as Full_Name,
count(distinct i.store_id) as store_count
from customer c   
inner join rental r on c.customer_id=r.customer_id
inner join inventory i  on r.inventory_id=i.inventory_id
inner join store s on i.store_id=s.store_id
group by c.customer_id
having store_count =2;

select 
r.customer_id,
count(distinct i.store_id) as Number_of_stores
from customer c   
inner join rental r on c.customer_id=r.customer_id
inner join inventory i  on r.inventory_id=i.inventory_id
inner join store s on i.store_id=s.store_id
group by r.customer_id
having Number_of_stores=2;

select * from customer;
select * from inventory;
select * from rental;
select * from store;

select c.customer_id,concat(c.first_name,' ',c.last_name) as Full_Name,count(distinct i.store_id) as Num_Of_Stores
from store s
inner join customer c on s.store_id=c.store_id
inner join rental r on c.customer_id=r.customer_id
inner join inventory i on r.inventory_id=i.inventory_id
group by c.customer_id
having Num_Of_Stores= (select count(distinct store_id) from store)
order by Full_Name ;



