##window in function

use mavenmovies;

/*1. Rank the customers based on the total amount they've spent on rentals.*/

select * from customer;
select * from rental;
select * from payment;

with Amit as (
select c.customer_id,
c.first_name ,
sum(p.amount) as total_amount_spent 
from customer c
join rental r on c.customer_id=r.customer_id
join payment p on r.rental_id=p.rental_id
group by c.customer_id
)
select customer_id,
total_amount_spent ,
dense_rank() over(order by  total_amount_spent desc) as customer_rank
from amit ;

/*2. Calculate the cumulative revenue generated by each film over time.*/

select * from film;
select * from rental;
select * from payment;
select * from inventory;

with harsha as (
select 
f.title ,
p.payment_date ,
p.amount,
sum(p.amount)as total_revenue,
rank() over(order by title )as cumulative_revenue
from harsha
group by f.title;
from rental r
inner join payment p on r.rental_id=p.rental_id
inner join inventory i on r.inventory_id=i.inventory_id
inner join film f on i.film_id=f.film_id
group by f.title
)
select 
title,


/*3. Determine the average rental duration for each film, considering films with similar lengths.*/

select * from film;
select * from rental;
select * from inventory;

with cte_1 as (
select 
f.film_id,
f.title,
f.length,
datediff(return_date, rental_date) as rental_duration
from film f
inner join inventory i on f.film_id=i.film_id
inner join rental r on i.inventory_id=r.inventory_id
),

cte_2 as (
select
film_id,
title,
length,
avg(rental_duration) as avg_rental_duration
from cte_1 
group by 
length,
title,
film_id
)

SELECT 
    title,
    length,
    AVG(avg_rental_duration) OVER (PARTITION BY length order by title) AS total_average_rental_duration
FROM cte_2
GROUP BY 
    title,
    length,
    avg_rental_duration;
 #######################################################################################################
 with rental_duration as(
select 
f.film_id,
f.title,
f.length,
datediff(r.return_date,r.rental_date) as rental_duration
From film f
inner join inventory i on f.film_id = i.film_id
inner join rental r on i.inventory_id = r.inventory_id
),

avg_rental as(
select
film_id,
title,
length,
avg(rental_duration) as avg_rental_duration
from rental_duration 
group by
film_id,
title,
length
),

cte_4 as (
select 
title,
length,
avg(avg_rental_duration) over(partition by length order by title)as total_average_rental
from avg_rental
),

cte_5 as (
select 
title ,
total_average_rental
from cte_4
where length=47),

cte_6 as(
select 
title 
from cte_5
where total_average_rental >4)

select 
title
from cte_6 
where left(title,1)="D";

 
/*4. *Identify the top 3 films in each category based on their rental counts.*/

select * from film;
select * from rental;
select * from category;
select* from film_category;
select * from inventory;

desc film_category;
with film_rental_count as (
select 
f.film_id,
f.title,
c.category_id,
c.name,
count(r.rental_id) AS rental_count
from film f
inner join film_category fc on f.film_id= fc.film_id
inner join category c on fc.category_id= c.category_id
inner join inventory i on f.film_id=i.film_id
inner join rental r on i.inventory_id= r.inventory_id 
    group by
    f.film_id,f.title,c.category_id,c.name
),
RankedFilms AS (
    SELECT
        film_id,
        title,
        category_id,
        name,
        rental_count,
        dense_rank() OVER (PARTITION BY category_id ORDER BY rental_count DESC) AS rental_rank
    FROM
        film_rental_count
)
SELECT
    film_id,
    title,
    category_id,
    name,
    rental_count,
    rental_rank
FROM
    RankedFilms
WHERE
    rental_rank <= 3;


/*5. Calculate the difference in rental counts between each customer's total rentals and the average rentals
across all customers.*/

select * from rental;
select * from customer;

WITH CustomerRentalCounts AS (
SELECT
        c.customer_id,
        COUNT(r.rental_id) AS rental_count
FROM  rental r 
inner join customer c on r.customer_id=c.customer_id
GROUP BY
c.customer_id
),
AverageRentalCount AS (
    SELECT
        AVG(rental_count) AS avg_rental_count
    FROM
        CustomerRentalCounts
)
SELECT
    crc.customer_id,
    crc.rental_count,
    (select avg_rental_count From AverageRentalCount) as rc_diff,
    crc.rental_count - (SELECT avg_rental_count FROM AverageRentalCount) AS rental_count_difference
FROM
    CustomerRentalCounts crc;

/*6. Find the monthly revenue trend for the entire rental store over time.*/

select * from rental;
select * from payment;

select 
DATE_FORMAT(r.rental_date, '%Y-%M') AS rental_month,
sum(p.amount) as total_revenue
from rental r 
inner join payment p on r.rental_id=p.rental_id
inner join customer c on p.customer_id=c.customer_id
group by rental_month;


/*7. **Identify the customers whose total spending on rentals falls within the top 20% of all customers.*/

select * from customer;
select * from rental;
select * from payment;

with customer_total_spending as (
 select 
 c.customer_id,
 concat(c.first_name," ",c.last_name) as full_name,
 sum(p.amount) as total_rental
from customer c
inner join rental r on c.customer_id=r.customer_id 
inner join payment p on r.rental_id=p.rental_id
group  by  c.customer_id,full_name
),
 
top_20per_cust as(
select 
customer_id,
full_name,
total_rental,
percent_rank() over(order by total_rental desc) as spending_per
from customer_total_spending 
)

select 
customer_id,
full_name,
total_rental,
spending_per * 100
from top_20per_cust
where spending_per <= 0.2 ;


/*8. **Calculate the running total of rentals per category, ordered by rental count.**/

select * from rental;
select * from category;
select * from film_category;
select * from inventory;
select * from film;

with category_rental_counts as (
select
c.category_id,
c.name,
count(r.rental_id) AS rental_count
from film f
inner join film_category fc on f.film_id= fc.film_id
inner join category c on fc.category_id= c.category_id
inner join inventory i on f.film_id=i.film_id
inner join rental r on i.inventory_id= r.inventory_id 
group by c.name,
c.category_id
)

SELECT 
category_id,
name ,
rental_count,
ROW_NUMBER() OVER (ORDER BY rental_count DESC) AS category_rank 
from category_rental_counts ;


/*9. Find the films that have been rented less than the average rental count for their respective categories.*/

select * from film;
select * from rental;
select * from film_category;
select * from inventory;


WITH film_rental_counts AS (
Select
f.film_id,
f.title,
fc.category_id,
COUNT(r.rental_id) AS total_rentals
From
film f
inner join film_category fc on f.film_id = fc.film_id
inner join inventory i on f.film_id = i.film_id
inner join rental r on i.inventory_id = r.inventory_id
Group by
	f.film_id,
	f.title,
	fc.category_id
),

category_average_rentals AS (
Select
	category_id,
    avg(total_rentals) as avg_total_rental
from
	film_rental_counts 
Group by
	category_id
)
select
category_id,
avg_total_rental,
select total_rentals from film_rental_counts
From 
category_average_rentals    
Wherex
total_rentals < avg_total_rental;


/*10. Identify the top 5 months with the highest revenue and display the revenue generated in each month.*/

select * from rental;
select * from payment;

with highest_monthlyrevenue as (
select 
DATE_FORMAT(payment_date, '%Y-%M') AS rental_month,
sum(amount) as total_revenue
from payment
group by rental_month
) 
select 
rental_month,
total_revenue 
from highest_monthlyrevenue
order by total_revenue desc limit 5;

##and 2nd way 

select 
DATE_FORMAT(payment_date, '%Y-%M') AS rental_month,
sum(amount) as total_revenue
from payment
group by rental_month 
order by total_revenue desc limit 5;

    
##*********************************************************************************************************************

/*1. Rank the customers based on the total amount they've spent on rentals.*/
/*2. Calculate the cumulative revenue generated by each film over time.*/
/*3. Determine the average rental duration for each film, considering films with similar lengths.*/
/*4. Identify the top 3 films in each category based on their rental counts.*/
/*5. Calculate the difference in rental counts between each customer's total rentals and the average rentals
across all customers.*/
/*6. Find the monthly revenue trend for the entire rental store over time.**
/*7. Identify the customers whose total spending on rentals falls within the top 20% of all customers.**
/*8. Calculate the running total of rentals per category, ordered by rental count.**
/*9. Find the films that have been rented less than the average rental count for their respective categories.**
/*10. Identify the top 5 months with the highest revenue and display the revenue generated in each month.**

